#!/bin/sh

echo -n "deletar arquivos inúteis [y/n]? "
read answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
    echo deletados arquivos inuteis
    rm -rf *.o
    rm -rf *.rej
    rm -rf *.orig
    rm -rf blocks.h
    rm -rf dwmblocks
fi
